#!/bin/bash

# Comprehensive Project Cleanup Script
# Generated on 2025-07-31T19:24:14.707Z

echo "🧹 Starting comprehensive project cleanup..."

# Create backup first
echo "📁 Creating backup..."
cp -r . ../designetica-backup-$(date +%Y%m%d_%H%M%S)

echo "🗑️ Removing backup and temporary files..."
rm "/Users/carlosmarinburgos/designetica/backend/.env.backup"
rm "/Users/carlosmarinburgos/designetica/backend/backups/HeroGenerator.js.backup.2025-07-28T14-48-35-325Z"
rm "/Users/carlosmarinburgos/designetica/backend/backups/HeroGenerator.js.backup.2025-07-28T14-48-42-924Z"
rm "/Users/carlosmarinburgos/designetica/backend/backups/HeroGenerator.js.backup.2025-07-28T16-53-53-001Z"
rm "/Users/carlosmarinburgos/designetica/backend/backups/HeroGenerator.js.backup.2025-07-28T16-56-08-486Z"
rm "/Users/carlosmarinburgos/designetica/backend/backups/HeroGenerator.js.backup.2025-07-29T00-38-30-782Z"
rm "/Users/carlosmarinburgos/designetica/backend/backups/local.settings.json.backup.2025-07-28T14-48-35-324Z"
rm "/Users/carlosmarinburgos/designetica/backend/backups/local.settings.json.backup.2025-07-28T14-48-42-923Z"
rm "/Users/carlosmarinburgos/designetica/backend/backups/local.settings.json.backup.2025-07-28T16-53-53-001Z"
rm "/Users/carlosmarinburgos/designetica/backend/backups/local.settings.json.backup.2025-07-28T16-56-08-485Z"
rm "/Users/carlosmarinburgos/designetica/backend/backups/local.settings.json.backup.2025-07-29T00-38-30-782Z"
rm "/Users/carlosmarinburgos/designetica/backend/backups/package.json.backup.2025-07-28T14-48-35-324Z"
rm "/Users/carlosmarinburgos/designetica/backend/backups/package.json.backup.2025-07-28T14-48-42-923Z"
rm "/Users/carlosmarinburgos/designetica/backend/backups/package.json.backup.2025-07-28T16-53-53-001Z"
rm "/Users/carlosmarinburgos/designetica/backend/backups/package.json.backup.2025-07-28T16-56-08-485Z"
rm "/Users/carlosmarinburgos/designetica/backend/backups/package.json.backup.2025-07-28T17-25-26-079Z"
rm "/Users/carlosmarinburgos/designetica/backend/backups/package.json.backup.2025-07-28T17-25-26-479Z"
rm "/Users/carlosmarinburgos/designetica/backend/backups/package.json.backup.2025-07-28T17-26-22-030Z"
rm "/Users/carlosmarinburgos/designetica/backend/backups/package.json.backup.2025-07-28T17-26-22-434Z"
rm "/Users/carlosmarinburgos/designetica/backend/backups/package.json.backup.2025-07-28T17-46-51-023Z"
rm "/Users/carlosmarinburgos/designetica/backend/backups/package.json.backup.2025-07-28T17-46-51-442Z"
rm "/Users/carlosmarinburgos/designetica/backend/backups/package.json.backup.2025-07-28T17-46-55-010Z"
rm "/Users/carlosmarinburgos/designetica/backend/backups/package.json.backup.2025-07-28T17-46-55-445Z"
rm "/Users/carlosmarinburgos/designetica/backend/backups/package.json.backup.2025-07-29T00-38-30-781Z"
rm "/Users/carlosmarinburgos/designetica/backend/backups/simple-server.js.backup.2025-07-28T14-48-35-315Z"
rm "/Users/carlosmarinburgos/designetica/backend/backups/simple-server.js.backup.2025-07-28T14-48-42-916Z"
rm "/Users/carlosmarinburgos/designetica/backend/backups/simple-server.js.backup.2025-07-28T15-08-47-764Z"
rm "/Users/carlosmarinburgos/designetica/backend/backups/simple-server.js.backup.2025-07-28T15-08-48-138Z"
rm "/Users/carlosmarinburgos/designetica/backend/backups/simple-server.js.backup.2025-07-28T15-10-15-773Z"
rm "/Users/carlosmarinburgos/designetica/backend/backups/simple-server.js.backup.2025-07-28T15-10-16-234Z"
rm "/Users/carlosmarinburgos/designetica/backend/backups/simple-server.js.backup.2025-07-28T16-53-52-981Z"
rm "/Users/carlosmarinburgos/designetica/backend/backups/simple-server.js.backup.2025-07-28T16-56-08-466Z"
rm "/Users/carlosmarinburgos/designetica/backend/backups/simple-server.js.backup.2025-07-29T00-38-30-775Z"
rm "/Users/carlosmarinburgos/designetica/backend/backups/simple-server.js.backup.2025-07-29T00-38-32-771Z"
rm "/Users/carlosmarinburgos/designetica/backend/generateWireframe/index.js.backup"
rm "/Users/carlosmarinburgos/designetica/backend/index.js.backup"
rm "/Users/carlosmarinburgos/designetica/backend/package.json.backup"
rm "/Users/carlosmarinburgos/designetica/src/App.css.backup"
rm "/Users/carlosmarinburgos/designetica/src/App.css.clean"
rm "/Users/carlosmarinburgos/designetica/src/App.tsx.backup"
rm "/Users/carlosmarinburgos/designetica/src/App_landing_PROTECTED.css"
rm "/Users/carlosmarinburgos/designetica/src/App_new.css"
rm "/Users/carlosmarinburgos/designetica/src/App_test.tsx"
rm "/Users/carlosmarinburgos/designetica/src/components/WireframeRenderer.tsx.new"
rm "/Users/carlosmarinburgos/designetica/src/config/api.ts.bak"
rm "/Users/carlosmarinburgos/designetica/staticwebapp.config.json.backup"

echo "🖼️ Removing unused assets..."
rm "/Users/carlosmarinburgos/designetica/public/VideoHero.png"
rm "/Users/carlosmarinburgos/designetica/public/bg.png"
rm "/Users/carlosmarinburgos/designetica/public/designetica-logo.svg"
rm "/Users/carlosmarinburgos/designetica/public/favicon-128x128.png"
rm "/Users/carlosmarinburgos/designetica/public/favicon-180x180.png"
rm "/Users/carlosmarinburgos/designetica/public/favicon-192x192.png"
rm "/Users/carlosmarinburgos/designetica/public/favicon-48x48.png"
rm "/Users/carlosmarinburgos/designetica/public/favicon-512x512.png"
rm "/Users/carlosmarinburgos/designetica/public/favicon-64x64.png"
rm "/Users/carlosmarinburgos/designetica/public/favicon.ico"
rm "/Users/carlosmarinburgos/designetica/public/logo.svg"
rm "/Users/carlosmarinburgos/designetica/public/vite.svg"

echo "🎨 Removing potentially unused CSS files..."
rm "/Users/carlosmarinburgos/designetica/src/App_clean.css"
rm "/Users/carlosmarinburgos/designetica/src/App_landing_PROTECTED.css"
rm "/Users/carlosmarinburgos/designetica/src/App_minimal.css"
rm "/Users/carlosmarinburgos/designetica/src/App_new.css"
rm "/Users/carlosmarinburgos/designetica/src/components/ImageAnalysisModal.css"
rm "/Users/carlosmarinburgos/designetica/src/components/LandingPageLayout.css"
rm "/Users/carlosmarinburgos/designetica/src/components/UnifiedComponentLibrary-new.css"
rm "/Users/carlosmarinburgos/designetica/src/styles/LinkableWireframe.css"
rm "/Users/carlosmarinburgos/designetica/src/styles/PageNavigation.css"
rm "/Users/carlosmarinburgos/designetica/src/styles/atlas-breadcrumb.css"
rm "/Users/carlosmarinburgos/designetica/src/styles/atlas-buttons.css"
rm "/Users/carlosmarinburgos/designetica/src/styles/atlas-cards.css"
rm "/Users/carlosmarinburgos/designetica/src/styles/atlas-design-system.css"
rm "/Users/carlosmarinburgos/designetica/src/styles/atlas-layout.css"
rm "/Users/carlosmarinburgos/designetica/src/styles/microsoftlearn-card.css"
rm "/Users/carlosmarinburgos/designetica/src/styles/navbar-footer.css"
rm "/Users/carlosmarinburgos/designetica/src/styles/responsive.css"
rm "/Users/carlosmarinburgos/designetica/src/styles/suggestion-indicator.css"
rm "/Users/carlosmarinburgos/designetica/src/styles/themes.css"
rm "/Users/carlosmarinburgos/designetica/src/styles/wireframe-content.css"

echo "🧪 Removing test and development files..."
rm "/Users/carlosmarinburgos/designetica/backend/azure-openai-test.js"
rm "/Users/carlosmarinburgos/designetica/backend/components/microsoftlearn-card-examples.js"
rm "/Users/carlosmarinburgos/designetica/backend/test-azure-functions.js"
rm "/Users/carlosmarinburgos/designetica/backend/test-cards.html"
rm "/Users/carlosmarinburgos/designetica/backend/test-course-cards-1.html"
rm "/Users/carlosmarinburgos/designetica/backend/test-course-cards-2.html"
rm "/Users/carlosmarinburgos/designetica/backend/test-course-cards-3.html"
rm "/Users/carlosmarinburgos/designetica/backend/test-course-cards-4.html"
rm "/Users/carlosmarinburgos/designetica/backend/test-course-cards-5.html"
rm "/Users/carlosmarinburgos/designetica/backend/test-course-cards.js"
rm "/Users/carlosmarinburgos/designetica/backend/test-course-gallery.html"
rm "/Users/carlosmarinburgos/designetica/backend/test-enhanced-ai.js"
rm "/Users/carlosmarinburgos/designetica/backend/test-fallback-cards.html"
rm "/Users/carlosmarinburgos/designetica/backend/test-form.html"
rm "/Users/carlosmarinburgos/designetica/backend/test-pill-1-azure-learning-path.html"
rm "/Users/carlosmarinburgos/designetica/backend/test-pill-2-dashboard.html"
rm "/Users/carlosmarinburgos/designetica/backend/test-pill-3-certification.html"
rm "/Users/carlosmarinburgos/designetica/backend/test-wireframe-no-banner.html"
rm "/Users/carlosmarinburgos/designetica/backend/test-wireframe.js"
rm "/Users/carlosmarinburgos/designetica/src/components/InteractiveWireframeExample.ts"
rm "/Users/carlosmarinburgos/designetica/test-atlas-breadcrumb.html"
rm "/Users/carlosmarinburgos/designetica/test-atlas-cards.html"
rm "/Users/carlosmarinburgos/designetica/test-deploy.html"
rm "/Users/carlosmarinburgos/designetica/test-fluent-ui-buttons.html"
rm "/Users/carlosmarinburgos/designetica/test-windows-logo.html"
rm "/Users/carlosmarinburgos/designetica/test-wireframe.html"

echo "✅ Cleanup complete!"
echo "📊 Removed 146 files"
echo "💾 Saved 1.87MB of space"
echo "🔙 Full backup saved in ../designetica-backup-*"
