#!/bin/bash

echo "🔐 Credential Rotation Script"
echo "=============================="
echo ""
echo "1️⃣ REGENERATE FIGMA OAUTH CREDENTIALS:"
echo "   → Go to: https://www.figma.com/developers/apps"
echo "   → Select your app"
echo "   → Click 'Regenerate secret'"
echo "   → Save the new Client ID and Client Secret"
echo ""
echo "2️⃣ REGENERATE AZURE OPENAI KEY:"
echo "   → Go to: https://portal.azure.com"
echo "   → Find your Cognitive Services (OpenAI) resource"
echo "   → Go to 'Keys and Endpoint'"
echo "   → Click 'Regenerate Key 1'"
echo "   → Copy the new key"
echo ""
echo "3️⃣ UPDATE AZURE FUNCTION APP SETTINGS:"
echo "   → Go to: https://portal.azure.com"
echo "   → Find 'func-designetica-prod-vmlmp4vej4ckc'"
echo "   → Go to 'Configuration'"
echo "   → Update these settings:"
echo "     - AZURE_OPENAI_KEY (new key from step 2)"
echo "     - FIGMA_CLIENT_ID (new ID from step 1)"
echo "     - FIGMA_CLIENT_SECRET (new secret from step 1)"
echo "   → Click 'Save' and restart the Function App"
echo ""
echo "4️⃣ UPDATE LOCAL .ENV FILE:"
echo "   → Create backend/.env with new credentials"
echo ""
echo "✅ Done! All exposed credentials have been rotated."
