const express = require('express');
const cors = require('cors');
const app = express();
const PORT = 7072;

app.use(cors());
app.use(express.json());

app.get('/api/health', (req, res) => {
  res.json({ status: 'healthy', timestamp: new Date().toISOString(), server: 'reliable-express' });
});

app.post('/api/fast-suggestions', (req, res) => {
  const { userInput } = req.body;
  console.log('🧠 AI Suggestions for:', userInput);
  
  const suggestions = [
    "Create a Microsoft Learn dashboard with progress tracking and certification paths",
    "Design Azure documentation pages with interactive code samples and tutorials", 
    "Build a learning path browser with role-based filtering and skill assessments",
    "Generate certification preparation hub with practice exams and study guides",
    "Create hands-on lab interface with Azure sandbox environment integration",
    "Design community Q&A platform with expert answers and discussion forums"
  ];
  
  res.json({
    suggestions,
    timestamp: new Date().toISOString(),
    source: 'reliable-express-server'
  });
});

app.post('/api/generate-wireframe', (req, res) => {
  const { description } = req.body;
  const html = `<!DOCTYPE html>
<html><head><title>Generated Wireframe</title>
<style>body{font-family:'Segoe UI',sans-serif;margin:40px;background:#f5f5f5}.container{max-width:800px;margin:0 auto;background:white;padding:2rem;border-radius:8px}h1{color:#0078d4}</style>
</head><body><div class="container"><h1>✅ Working Wireframe</h1><p><strong>Description:</strong> ${description || 'No description'}</p><p>Generated by reliable Express server - no more Azure Functions issues!</p></div></body></html>`;
  
  res.json({ html, timestamp: new Date().toISOString(), generatedBy: 'ReliableExpress' });
});

app.listen(PORT, () => {
  console.log(`🎉 RELIABLE EXPRESS SERVER RUNNING ON http://localhost:${PORT}`);
  console.log(`✅ Health: http://localhost:${PORT}/api/health`);
  console.log(`🧠 AI Suggestions: http://localhost:${PORT}/api/fast-suggestions`);
  console.log(`🎯 Wireframes: http://localhost:${PORT}/api/generate-wireframe`);
  console.log(`📱 Your frontend will connect automatically!`);
});
