#!/bin/bash

echo "📄 MARKDOWN DOCUMENTATION CLEANUP ANALYSIS"
echo "=========================================="
echo ""
echo "Current MD files: $(ls *.md | wc -l)"
echo ""

echo "🎯 RECOMMENDED ACTIONS:"
echo ""

echo "1. 🗑️  DELETE STATUS/COMPLETION FILES (10 files):"
echo "   These are outdated status reports that served their purpose:"
echo "   - AZURE_ENDPOINT_UPDATE_COMPLETE.md"
echo "   - BACKUP_COMPLETION_STATUS.md"
echo "   - FINAL_TRANSFER_STATUS.md"
echo "   - FRONTEND_UPDATES_COMPLETE.md"
echo "   - OFFLINE_MODE_FIXED.md"
echo "   - PHASE_3_COMPLETION_SUMMARY.md"
echo "   - POWER_APPS_INTEGRATION_BACKUP_SUMMARY.md"
echo "   - POWER_PLATFORM_INTEGRATION_COMPLETE.md"
echo "   - PRODUCTION_OUTAGE_STATUS.md"
echo "   - REAL_TIME_REFINEMENT_SUMMARY.md"
echo ""

echo "2. 🗑️  DELETE OBSOLETE PROJECT PHASE FILES (5 files):"
echo "   These were for specific project phases now complete:"
echo "   - MICROSOFT_TRANSFER_GUIDE.md"
echo "   - MICROSOFT_TRANSFER_PACKAGE.md"
echo "   - PHASE_4_PRODUCTION_DEPLOYMENT.md"
echo "   - PHASE_4_PROGRESS_TRACKER.md"
echo "   - TRANSFER_CHECKLIST.md"
echo ""

echo "3. 🗑️  DELETE QUICK FIX/UPDATE FILES (5 files):"
echo "   These were for specific issues now resolved:"
echo "   - COMPACT_TOOLBAR_UPDATES.md"
echo "   - IMAGE_PLACEHOLDER_FIXES.md"
echo "   - MISSING_IMAGES.md"
echo "   - PHASE_4_SKU_FIX.md"
echo "   - REACT_COMPONENTS_CLEANUP.md"
echo ""

echo "4. 📁 MOVE TO docs/ FOLDER (Keep but organize):"
echo "   Important guides that should be preserved:"
echo "   - DEPLOYMENT_GUIDE.md"
echo "   - DEPLOYMENT_CONFIGURATION_GUIDE.md"
echo "   - DEVELOPMENT_GUIDE.md"
echo "   - EMERGENCY_RECOVERY_PLAN.md"
echo "   - PERFORMANCE_OPTIMIZATION.md"
echo "   - PRODUCTION_DEPLOYMENT_GUIDE.md"
echo "   - REARRANGEABLE_WIREFRAME_GUIDE.md"
echo ""

echo "5. ✅ KEEP IN ROOT (Essential files):"
echo "   - README.md (main project documentation)"
echo ""

echo "📊 CLEANUP IMPACT:"
echo "   - Files to delete: ~20"
echo "   - Files to move to docs/: ~7"
echo "   - Files to keep in root: ~1"
echo "   - Reduction: ~60% fewer MD files in root"
echo ""

echo "🚨 SAFETY NOTE:"
echo "   All files will be backed up before deletion"
echo ""

echo "💡 EXECUTION PLAN:"
echo "   1. Create backup"
echo "   2. Create docs/ folder"
echo "   3. Move important guides to docs/"
echo "   4. Delete status/obsolete files"
echo "   5. Verify cleanup"
